config/routes.rb
Dishalish::Application.routes.draw do
  root 'restaurants#index'

  resources :dishes

  devise_for :users
  resources :restaurants

end

app/models/dish.rb
class Dish < ActiveRecord::Base
	belongs_to :restaurant
	has_many :ratings
end

app/models/ratings.rb
class Ratings < ActiveRecord::Base
	belongs_to :dish
	belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :dishes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ratings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
    @restaurant = Restaurant.find(params[:rest])
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dish }
      else
        format.html { render action: 'new' }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:restaurant_id, :price, :name, :description)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @restaurant }
      else
        format.html { render action: 'new' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :zip, :cuisine, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.number_field :restaurant_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.number_field :restaurant_id, :value => @restaurant.id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', @restaurant %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant:</strong>
  <%= @dish.restaurant_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', restaurant_path(@dish.restaurant) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= content_for?(:title) ? yield(:title) : "Dishalish" %></title>
	<%= csrf_meta_tags %>

	<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
	<!--[if lt IE 9]>
	  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
	<![endif]-->

	<%= stylesheet_link_tag "application", :media => "all" %>

	<!-- For third-generation iPad with high-resolution Retina display: -->
	<!-- Size should be 144 x 144 pixels -->
	<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

	<!-- For iPhone with high-resolution Retina display: -->
	<!-- Size should be 114 x 114 pixels -->
	<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

	<!-- For first- and second-generation iPad: -->
	<!-- Size should be 72 x 72 pixels -->
	<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

	<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
	<!-- Size should be 57 x 57 pixels -->
	<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

	<!-- For all other devices -->
	<!-- Size should be 32 x 32 pixels -->
	<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

	<div class="navbar navbar-fluid-top">
	  <div class="navbar-inner">
		<div class="container-fluid">
		  <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </a>
		  <a class="brand" href="/">Dishalish</a>
		  <div class="container-fluid nav-collapse">
			<ul class="nav">
			  <li><%= link_to "Restaurants", restaurants_path  %></li>
			  <%if signed_in? %>
				<li><%= link_to current_user.email, '#'  %></li>
				<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
			  <%else%>
			  	<li><%=link_to 'Sign In', new_user_session_path%></li>
			  	<li><%=link_to 'Sign Up', new_user_registration_path%></li>
			  <%end%>
			</ul>
		  </div><!--/.nav-collapse -->
		</div>
	  </div>
	</div>

	<div class="container-fluid">
	  <div class="row-fluid">
<!--        <div class="span3">
		  <div class="well sidebar-nav">
			<ul class="nav nav-list">
			  <li class="nav-header">Sidebar</li>
			  <li><%= link_to "Link1", "/path1"  %></li>
			  <li><%= link_to "Link2", "/path2"  %></li>
			  <li><%= link_to "Link3", "/path3"  %></li>
			</ul>
		  </div><!--/.well -->
		</div><!--/span-->
		<div class="span12">
		  <%= bootstrap_flash %>
		  <%= yield %>
		</div>
	  </div><!--/row-->

	  <footer style="text-align:center">
		<p>&copy; Company 2013</p>
	  </footer>

	</div> <!-- /container -->

	<!-- Javascripts
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<%= javascript_include_tag "application" %>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for (@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :zip %>
  <%= f.input :cuisine %>
  <%= f.input :price %>
  <%= f.button :submit %>
<% end %>


<!--<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :cuisine %><br>
    <%= f.text_field :cuisine %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>-->

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Overview</h1>

<table class="table table striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Address</th>
			<th>Zip</th>
			<th>Cuisine</th>
			<th>Price</th>
			<% if signed_in?%>
				<th></th>
				<th></th>
				<th></th>
			<%end%>
		</tr>
	</thead>

	<tbody>
		<% @restaurants.each do |restaurant| %>
			<tr>
				<td><%= link_to restaurant.name, restaurant %></td>
				<td><%= restaurant.address %></td>
				<td><%= restaurant.zip %></td>
				<td><%= restaurant.cuisine %></td>
				<td><%= restaurant.price %></td>
				<%if signed_in? %>
					<td><%= link_to 'New Dish', new_dish_path(:rest=>restaurant.id)%></td>
					<td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
					<td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<%end%>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Name:</strong>
	<%= @restaurant.name %>
</p>

<p>
	<strong>Address:</strong>
	<%= @restaurant.address %>
</p>

<p>
	<strong>Zip:</strong>
	<%= @restaurant.zip %>
</p>

<p>
	<strong>Cuisine:</strong>
	<%= @restaurant.cuisine %>
</p>

<p>
	<strong>Price:</strong>
	<%= @restaurant.price %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

<br><br>

<h3>Dishes</h3>
<table class="table table-striped">
	<thead>
		<th>Name</th>
		<th>Price</th>
		<th>Description</th>
		<th></th>
		<th></th>
	</thead>
	<tbody>
		<%@restaurant.dishes.each do |dish|%>
			<tr>
				<td><%=link_to dish.name, dish_path(dish)%></td>
				<td><%=dish.price%></td>
				<td><%=dish.description%></td>
				<td><%=link_to 'Edit', edit_dish_path%></td>
				<td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<%end%>
	</tbody>
</table>
<%= link_to 'New Dish', new_dish_path(:rest=>@restaurant.id)%></td>